# Generated by Django 3.1.5 on 2021-01-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='master_password',
            field=models.CharField(default='DEFAULT', max_length=200),
        ),
    ]
