# Generated by Django 3.1 on 2021-01-06 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='creared',
        ),
        migrations.RemoveField(
            model_name='location',
            name='website',
        ),
        migrations.AddField(
            model_name='location',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='main_user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='website_name',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='website_notes',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='website_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='website_password',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='website_username',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
    ]
