# Generated by Django 3.1.5 on 2021-01-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_location_master_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='master_password',
            field=models.CharField(default='Main Password', max_length=200),
        ),
    ]
