# Generated by Django 3.1 on 2021-01-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210106_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='website_notes',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
