# Generated by Django 3.1.5 on 2021-01-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210113_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='master_password',
            field=models.CharField(default='', max_length=200),
        ),
    ]
