# Generated by Django 3.1.5 on 2021-01-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210118_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='website_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='website_name',
            field=models.CharField(max_length=50),
        ),
    ]
